package tokenstore

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
)

// FileStore stores tokens in AES-256-GCM-encrypted files, one file per
// reference, under a single directory. It is the encrypted fallback when
// PostgreSQL is not configured; the key is derived from GITSAFE_TOKEN_KEY.
//
// References are per-user (see GitHubTokenFor/DriveTokenFor), so distinct
// accounts never share a file. Files are written with 0600 permissions in a
// 0700 directory. A missing file maps to ErrNotFound; a tampered or
// unreadable file surfaces an explicit decrypt/corruption error rather than an
// empty token.
type FileStore struct {
	dir string
	key [32]byte
}

// fileToken is the on-disk envelope: the random nonce and the sealed ciphertext.
// JSON marshals []byte as base64, keeping values secret outside the AES layer.
type fileToken struct {
	Version    int    `json:"version"`
	Nonce      []byte `json:"nonce"`
	Ciphertext []byte `json:"ciphertext"`
}

// NewFileStore creates an encrypted file store rooted at dir. The key material
// is hashed with SHA-256 to a fixed-size AES-256 key, so any memorable secret
// of any length is accepted.
func NewFileStore(dir, keyMaterial string) (*FileStore, error) {
	if keyMaterial == "" {
		return nil, errors.New("tokenstore: file store requires a non-empty key")
	}
	if dir == "" {
		return nil, errors.New("tokenstore: file store requires a directory")
	}
	key, err := deriveTokenKey(keyMaterial)
	if err != nil {
		return nil, fmt.Errorf("tokenstore: file store: %w", err)
	}
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return nil, fmt.Errorf("tokenstore: create store directory: %w", err)
	}
	return &FileStore{dir: dir, key: key}, nil
}

// pathFor maps a reference to its on-disk file. References are generated by
// code (alphanumerics, dot, dash), but the filename is hardened anyway so a
// malformed reference can never escape the store directory.
func (f *FileStore) pathFor(ref string) string {
	name := make([]byte, 0, len(ref))
	for i := 0; i < len(ref); i++ {
		c := ref[i]
		switch {
		case c >= 'a' && c <= 'z', c >= 'A' && c <= 'Z', c >= '0' && c <= '9', c == '.', c == '-', c == '_':
			name = append(name, c)
		default:
			name = append(name, '_')
		}
	}
	return filepath.Join(f.dir, string(name)+".json")
}

// Set encrypts value and writes it under reference.
func (f *FileStore) Set(ref, value string) error {
	if ref == "" {
		return errors.New("tokenstore: empty reference")
	}
	nonce, ciphertext, err := encryptToken(f.key, value)
	if err != nil {
		return err
	}
	data, err := json.Marshal(fileToken{Version: 1, Nonce: nonce, Ciphertext: ciphertext})
	if err != nil {
		return err
	}
	if err := os.MkdirAll(f.dir, 0o700); err != nil {
		return err
	}
	path := f.pathFor(ref)
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0o600); err != nil {
		return fmt.Errorf("tokenstore: write %q: %w", ref, err)
	}
	// Atomic rename so a reader never observes a half-written token.
	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("tokenstore: commit %q: %w", ref, err)
	}
	return nil
}

// Get returns the token stored under reference. A missing file returns
// ErrNotFound; a corrupt or tampered file returns an explicit error.
func (f *FileStore) Get(ref string) (string, error) {
	if ref == "" {
		return "", errors.New("tokenstore: empty reference")
	}
	path := f.pathFor(ref)
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return "", ErrNotFound
		}
		return "", fmt.Errorf("tokenstore: read %q: %w", ref, err)
	}
	var ft fileToken
	if err := json.Unmarshal(data, &ft); err != nil {
		return "", fmt.Errorf("tokenstore: corrupt token file %q: %w", ref, err)
	}
	value, err := decryptToken(f.key, ft.Nonce, ft.Ciphertext)
	if err != nil {
		if len(ft.Nonce) != tokenNonceSize {
			return "", fmt.Errorf("tokenstore: corrupt token file %q: bad nonce length", ref)
		}
		return "", fmt.Errorf("tokenstore: decrypt %q: %w", ref, err)
	}
	return value, nil
}

// Delete removes the token stored under reference. A missing reference is a
// no-op success, mirroring KeyringStore.
func (f *FileStore) Delete(ref string) error {
	if ref == "" {
		return errors.New("tokenstore: empty reference")
	}
	err := os.Remove(f.pathFor(ref))
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("tokenstore: delete %q: %w", ref, err)
	}
	return nil
}
